/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;
import manager.controller.AppRunner;
import manager.controller.EstateController;
import manager.model.estate.Estate;
import manager.model.estate.EstateModel;
/**
 *
 * @author virtus
 */
public class BasicFrame extends javax.swing.JFrame {
    /**
     * Creates new form Manager
     */
    public BasicFrame() {
           
        initComponents();
    }
    Estate p = new Estate();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmbManager = new javax.swing.JMenuBar();
        jmProperties = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikacja dla administratora nieruchomosci");
        setAlwaysOnTop(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jmProperties.setText("Nieruchomosci");
        jmProperties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmPropertiesMouseClicked(evt);
            }
        });
        jmbManager.add(jmProperties);

        setJMenuBar(jmbManager);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1108, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmPropertiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmPropertiesMouseClicked
//          new EstateDialog(this,false).setVisible(true);
        AppRunner.createEstateDialog();
    }//GEN-LAST:event_jmPropertiesMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmProperties;
    private javax.swing.JMenuBar jmbManager;
    // End of variables declaration//GEN-END:variables


}
