/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager.view;

/**
 *
 * @author virtus
 */
public class Kontrachenci extends javax.swing.JDialog {

    /**
     * Creates new form Kontrachenci
     */
    public Kontrachenci(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbKontrachent = new javax.swing.JToolBar();
        btNowyKontrachent = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        tbFile = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        spKontrachent = new javax.swing.JScrollPane();
        tabKontrachent = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kontrachenci");

        tbKontrachent.setRollover(true);
        tbKontrachent.setEnabled(false);

        btNowyKontrachent.setText("Nowy kontrachent");
        btNowyKontrachent.setFocusable(false);
        btNowyKontrachent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNowyKontrachent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbKontrachent.add(btNowyKontrachent);

        jButton3.setText("Nowa Grupa");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbKontrachent.add(jButton3);

        jLabel1.setText("    Nazwa:");
        tbKontrachent.add(jLabel1);
        tbKontrachent.add(jTextField1);

        jLabel2.setText("Miejscowosc:");
        tbKontrachent.add(jLabel2);

        tbKontrachent.add(jComboBox1);

        jLabel3.setText("Kod pocztowy:");
        tbKontrachent.add(jLabel3);
        tbKontrachent.add(jTextField2);

        jLabel4.setText("Ulica:");
        tbKontrachent.add(jLabel4);
        tbKontrachent.add(jTextField3);

        jLabel5.setText("Telefon:");
        tbKontrachent.add(jLabel5);
        tbKontrachent.add(jTextField4);

        tbFile.setRollover(true);
        tbFile.setEnabled(false);
        tbFile.add(filler1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/pdf.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbFile.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/excel.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbFile.add(jButton2);

        spKontrachent.setBorder(javax.swing.BorderFactory.createTitledBorder("Kontrachenci"));

        tabKontrachent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Nazwa:", "Miejscowość:", "Kod pocztowy:", "Ulica:", "Telefon:"
            }
        ));
        tabKontrachent.setFillsViewportHeight(true);
        spKontrachent.setViewportView(tabKontrachent);
        if (tabKontrachent.getColumnModel().getColumnCount() > 0) {
            tabKontrachent.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbKontrachent, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
                    .addComponent(tbFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spKontrachent))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbKontrachent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbFile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spKontrachent, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNowyKontrachent;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JScrollPane spKontrachent;
    private javax.swing.JTable tabKontrachent;
    private javax.swing.JToolBar tbFile;
    private javax.swing.JToolBar tbKontrachent;
    // End of variables declaration//GEN-END:variables
}
