/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager.view;

/**
 *
 * @author virtus
 */
public class Raporty extends javax.swing.JDialog {

    /**
     * Creates new form Raporty
     */
    public Raporty(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spRaporty = new javax.swing.JScrollPane();
        tabRaporty = new javax.swing.JTable();
        tbRaportyAkcja = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        tbFile = new javax.swing.JToolBar();
        labWykres = new javax.swing.JLabel();
        btWykres = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btPdf = new javax.swing.JButton();
        btExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Raporty");

        spRaporty.setBorder(javax.swing.BorderFactory.createTitledBorder("Raporty"));

        tabRaporty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Numer:", "Towar/Usługa", "Ilosc:", "Ost.Cena.Zakupu", "Ost.Data.Zakupu", "Ost.Spr.Brutto", "Grupa"
            }
        ));
        tabRaporty.setFillsViewportHeight(true);
        spRaporty.setViewportView(tabRaporty);

        tbRaportyAkcja.setEnabled(false);

        jButton1.setText("Dodaj Raport");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbRaportyAkcja.add(jButton1);
        tbRaportyAkcja.add(jSeparator1);

        jLabel1.setText("        Towar/Usluga:");
        tbRaportyAkcja.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tbRaportyAkcja.add(jComboBox1);

        jLabel2.setText("Ilosc:");
        tbRaportyAkcja.add(jLabel2);
        tbRaportyAkcja.add(jSpinner1);

        jLabel3.setText("Ost.Cena.Zakupu:");
        tbRaportyAkcja.add(jLabel3);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel());
        tbRaportyAkcja.add(jSpinner2);

        jLabel4.setText("Ost.Data.zakupu:");
        tbRaportyAkcja.add(jLabel4);

        jSpinner3.setModel(new javax.swing.SpinnerDateModel());
        tbRaportyAkcja.add(jSpinner3);

        jLabel5.setText("Ost.Spr.Brutto:");
        tbRaportyAkcja.add(jLabel5);
        tbRaportyAkcja.add(jSpinner4);

        jLabel6.setText("Grupa:");
        tbRaportyAkcja.add(jLabel6);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        tbRaportyAkcja.add(jComboBox2);

        tbFile.setRollover(true);
        tbFile.setToolTipText("");
        tbFile.setEnabled(false);

        labWykres.setText("Wykres:");
        tbFile.add(labWykres);

        btWykres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/chart.png"))); // NOI18N
        btWykres.setFocusable(false);
        btWykres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btWykres.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbFile.add(btWykres);
        tbFile.add(filler1);

        btPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/pdf.png"))); // NOI18N
        btPdf.setFocusable(false);
        btPdf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btPdf.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tbFile.add(btPdf);

        btExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/excel.png"))); // NOI18N
        btExcel.setFocusable(false);
        btExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbFile.add(btExcel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spRaporty, javax.swing.GroupLayout.DEFAULT_SIZE, 1159, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbRaportyAkcja, javax.swing.GroupLayout.DEFAULT_SIZE, 1149, Short.MAX_VALUE)
                            .addComponent(tbFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbRaportyAkcja, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spRaporty, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcel;
    private javax.swing.JButton btPdf;
    private javax.swing.JButton btWykres;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JLabel labWykres;
    private javax.swing.JScrollPane spRaporty;
    private javax.swing.JTable tabRaporty;
    private javax.swing.JToolBar tbFile;
    private javax.swing.JToolBar tbRaportyAkcja;
    // End of variables declaration//GEN-END:variables
}
