/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager.view.estate;

import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
import manager.controller.AppRunner;
import manager.controller.EstateController;
import manager.controller.PersonController;
import manager.model.estate.EstateTableModel;

/**
 *
 * @author virtus
 */
public class EstateDialog extends javax.swing.JDialog implements Observer {

    private final EstateController controller;
    private final PersonController personController;
    
    private int currentSelectedRowIndex;
    private int[] currentSelectedRowsIndex;
    private File img;
    private final int IMG_W = 100;
    private final int IMG_H = 100;
    private TableRowSorter<EstateTableModel> sorter;

    
    public EstateDialog(){
        controller = null;
        personController = null;
        initComponents();
    }
     /**
     * Creates new form Properties
     *
     * @param controller
     * @param parent
     * @param modal
     */
    public EstateDialog(EstateController controller,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.controller = controller;
        this.personController = new PersonController();
        initComponents();
        mySettingComponent();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jdAddProperty = new javax.swing.JDialog();
        jpDProperty = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jlabDNewEstate = new javax.swing.JLabel();
        jlabDNameEstate = new javax.swing.JLabel();
        jtfDName = new javax.swing.JTextField();
        jlabDTid = new javax.swing.JLabel();
        jcbTid = new javax.swing.JComboBox<>();
        jlabDPrice = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jspDDescription = new javax.swing.JScrollPane();
        jtaDDescription = new javax.swing.JTextArea();
        jlabDCountry = new javax.swing.JLabel();
        jlabDProvince = new javax.swing.JLabel();
        jtfDProvince = new javax.swing.JTextField();
        jlabDCommunity = new javax.swing.JLabel();
        jtfDCommunity = new javax.swing.JTextField();
        jlabDCounty = new javax.swing.JLabel();
        jtfDCounty = new javax.swing.JTextField();
        jlabDCity = new javax.swing.JLabel();
        jtfDCity = new javax.swing.JTextField();
        jlabDStreet = new javax.swing.JLabel();
        jtfDStreet = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jbAddEstate = new javax.swing.JButton();
        jbCancelEstate = new javax.swing.JButton();
        jtfDCountry = new javax.swing.JTextField();
        jlabChoosePic = new javax.swing.JLabel();
        btChoosePic = new javax.swing.JButton();
        jtfDPrice = new javax.swing.JTextField();
        jtfDSurface = new javax.swing.JTextField();
        jtfDRooms = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jcbNid = new javax.swing.JComboBox<>();
        tbProperties = new javax.swing.JToolBar();
        btAddProperty = new javax.swing.JButton();
        btPDF = new javax.swing.JButton();
        btExcel = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jspProperties = new javax.swing.JSplitPane();
        jpView = new javax.swing.JPanel();
        jpViewProperties = new javax.swing.JPanel();
        jlabResourceName = new javax.swing.JLabel();
        jlabResourceEmptyPlace = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtrResources = new javax.swing.JTree();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        personsPanel = personController.getPersonPanel();
        mediaPanel1 = new manager.view.estate.panel.MediaPanel();
        renovationPanel1 = new manager.view.estate.panel.RenovationPanel();
        equipmentPanel1 = new manager.view.estate.panel.EquipmentPanel();
        tablePanel = controller.getTablePanel();
        manager.view.estate.panel.LocalPanel localPanel = controller.getLocalPanel();
        fillterPanel = controller.getFillterPanel();

        jdAddProperty.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jdAddProperty.setTitle("Dodaj Nieruchomosc");
        jdAddProperty.setAlwaysOnTop(true);
        jdAddProperty.setFocusTraversalPolicyProvider(true);
        jdAddProperty.setSize(new java.awt.Dimension(500, 500));

        jpDProperty.setBackground(new java.awt.Color(255, 255, 255));
        jpDProperty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jlabDNewEstate.setText("Nowa nieruchomosc:");

        jlabDNameEstate.setText("Nazwa:");

        jlabDTid.setText("Typ transakcji:");

        jcbTid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sprzedaz", "Wynajem" }));
        jcbTid.setSelectedIndex(-1);

        jlabDPrice.setText("Cena:");

        jLabel14.setText("Powierzchnia:");

        jLabel15.setText("Licz.pokoi");

        jLabel16.setText("Opis:");

        jtaDDescription.setColumns(20);
        jtaDDescription.setRows(5);
        jspDDescription.setViewportView(jtaDDescription);

        jlabDCountry.setText("Kraj:");

        jlabDProvince.setText("Wojwodztwo:");

        jlabDCommunity.setText("Gmina:");

        jlabDCounty.setText("Powiat:");

        jlabDCity.setText("Miasto:");

        jtfDCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDCityActionPerformed(evt);
            }
        });

        jlabDStreet.setText("Ulica:");

        jbAddEstate.setText("Dodaj");
        jbAddEstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddEstateActionPerformed(evt);
            }
        });

        jbCancelEstate.setText("Anuluj");
        jbCancelEstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelEstateActionPerformed(evt);
            }
        });

        jlabChoosePic.setText("Zdiecie:");

        btChoosePic.setText("Wybierz zdiecie...");
        btChoosePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChoosePicActionPerformed(evt);
            }
        });

        jLabel12.setText("Typ nieruchomosc:i");

        jcbNid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartament", "Mieszkanie", "Biuro", "Dzialka", "Dom", "inne" }));
        jcbNid.setSelectedIndex(-1);

        javax.swing.GroupLayout jpDPropertyLayout = new javax.swing.GroupLayout(jpDProperty);
        jpDProperty.setLayout(jpDPropertyLayout);
        jpDPropertyLayout.setHorizontalGroup(
            jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jpDPropertyLayout.createSequentialGroup()
                .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDPropertyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlabDNewEstate))
                    .addGroup(jpDPropertyLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabDTid)
                            .addComponent(jlabDPrice)
                            .addComponent(jLabel14)
                            .addComponent(jlabDNameEstate)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDName)
                            .addComponent(jcbTid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jspDDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jtfDPrice)
                            .addComponent(jtfDSurface)
                            .addComponent(jtfDRooms)
                            .addComponent(jcbNid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(47, 47, 47)
                .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDPropertyLayout.createSequentialGroup()
                        .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabDProvince)
                            .addComponent(jlabDCommunity)
                            .addComponent(jlabDCounty)
                            .addComponent(jlabDCity)
                            .addComponent(jlabDStreet)
                            .addComponent(jlabDCountry))
                        .addGap(18, 18, 18)
                        .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDProvince, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jtfDCommunity)
                            .addComponent(jtfDCounty)
                            .addComponent(jtfDCity)
                            .addComponent(jtfDStreet)
                            .addComponent(jtfDCountry)))
                    .addGroup(jpDPropertyLayout.createSequentialGroup()
                        .addComponent(jlabChoosePic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btChoosePic, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDPropertyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbAddEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jpDPropertyLayout.setVerticalGroup(
            jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDPropertyLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlabDNewEstate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabDNameEstate)
                    .addComponent(jtfDName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabDCountry)
                    .addComponent(jtfDCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabDTid)
                    .addComponent(jcbTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabDProvince)
                    .addComponent(jtfDProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jcbNid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabDPrice)
                    .addComponent(jlabDCommunity)
                    .addComponent(jtfDCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlabDCounty)
                    .addComponent(jtfDCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDSurface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDPropertyLayout.createSequentialGroup()
                        .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jlabDCity)
                            .addComponent(jtfDCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabDStreet)
                            .addComponent(jtfDStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabChoosePic)
                            .addComponent(btChoosePic)))
                    .addGroup(jpDPropertyLayout.createSequentialGroup()
                        .addComponent(jtfDRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspDDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jpDPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAddEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelEstate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdAddPropertyLayout = new javax.swing.GroupLayout(jdAddProperty.getContentPane());
        jdAddProperty.getContentPane().setLayout(jdAddPropertyLayout);
        jdAddPropertyLayout.setHorizontalGroup(
            jdAddPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddPropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDProperty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdAddPropertyLayout.setVerticalGroup(
            jdAddPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddPropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDProperty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nieruchomosci");
        setUndecorated(true);

        tbProperties.setFloatable(false);
        tbProperties.setRollover(true);

        btAddProperty.setBackground(new java.awt.Color(204, 204, 204));
        btAddProperty.setForeground(new java.awt.Color(102, 102, 102));
        btAddProperty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/add.png"))); // NOI18N
        btAddProperty.setText("Dodaj nieruchomosc");
        btAddProperty.setToolTipText("Dodaj nowa nieruchomosc");
        btAddProperty.setFocusable(false);
        btAddProperty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAddProperty.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAddProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPropertyActionPerformed(evt);
            }
        });
        tbProperties.add(btAddProperty);

        btPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/pdf.png"))); // NOI18N
        btPDF.setFocusable(false);
        btPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbProperties.add(btPDF);

        btExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon/excel.png"))); // NOI18N
        btExcel.setFocusable(false);
        btExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbProperties.add(btExcel);

        jSplitPane2.setDividerSize(12);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setOneTouchExpandable(true);

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane1.setDividerLocation(900);
        jSplitPane1.setDividerSize(12);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setOneTouchExpandable(true);

        jspProperties.setBackground(new java.awt.Color(255, 255, 255));
        jspProperties.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jspProperties.setDividerLocation(500);
        jspProperties.setDividerSize(12);
        jspProperties.setForeground(new java.awt.Color(204, 204, 204));
        jspProperties.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jspProperties.setResizeWeight(0.99999999);
        jspProperties.setToolTipText("");
        jspProperties.setAutoscrolls(true);
        jspProperties.setContinuousLayout(true);
        jspProperties.setOneTouchExpandable(true);
        jspProperties.setPreferredSize(new java.awt.Dimension(94, 800));

        jpView.setAutoscrolls(true);

        jpViewProperties.setBackground(new java.awt.Color(255, 255, 255));
        jpViewProperties.setAutoscrolls(true);

        jlabResourceName.setText("Zasoby:");

        jtrResources.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jtrResources.setForeground(new java.awt.Color(255, 255, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Nieruchomosc");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Osoby");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Administratorzy");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Lokatorzy");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Media");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Prad");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Gaz");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Internet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Inne");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Remonty");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Aktualne");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ukonczone");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jtrResources.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtrResources.setToolTipText("");
        jtrResources.setAutoscrolls(true);
        jtrResources.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jtrResources);

        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane2.setToolTipText("");
        jTabbedPane2.setAutoscrolls(true);
        jTabbedPane2.addTab("Osoby:", personsPanel);
        jTabbedPane2.addTab("Media:", mediaPanel1);
        jTabbedPane2.addTab("Remonty:", renovationPanel1);
        jTabbedPane2.addTab("Wyposazenie:", equipmentPanel1);

        javax.swing.GroupLayout jpViewPropertiesLayout = new javax.swing.GroupLayout(jpViewProperties);
        jpViewProperties.setLayout(jpViewPropertiesLayout);
        jpViewPropertiesLayout.setHorizontalGroup(
            jpViewPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jpViewPropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpViewPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpViewPropertiesLayout.createSequentialGroup()
                        .addComponent(jlabResourceName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlabResourceEmptyPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpViewPropertiesLayout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpViewPropertiesLayout.setVerticalGroup(
            jpViewPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpViewPropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpViewPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabResourceName)
                    .addComponent(jlabResourceEmptyPlace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpViewPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpViewLayout = new javax.swing.GroupLayout(jpView);
        jpView.setLayout(jpViewLayout);
        jpViewLayout.setHorizontalGroup(
            jpViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpViewProperties, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpViewLayout.setVerticalGroup(
            jpViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpViewLayout.createSequentialGroup()
                .addComponent(jpViewProperties, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jspProperties.setRightComponent(jpView);

        tablePanel.setAutoscrolls(true);
        jspProperties.setLeftComponent(tablePanel);

        jSplitPane1.setLeftComponent(jspProperties);
        jSplitPane1.setRightComponent(localPanel);

        jSplitPane2.setRightComponent(jSplitPane1);
        jSplitPane2.setLeftComponent(fillterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbProperties, javax.swing.GroupLayout.DEFAULT_SIZE, 1127, Short.MAX_VALUE)
                    .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1127, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbProperties, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mySettingComponent(){
        jpView.setVisible(false);
    }
    
    public void setView(boolean t){
        jpView.setVisible(t);
    }
    
    public void setResourceName(String name){
        jlabResourceEmptyPlace.setText(name);
    
    }
    
    private void setCellEditors(){
        JTextField jtfEName = new JTextField();
        JComboBox jcbENid = new JComboBox(new String[]{" ","Apartament", "Mieszkanie", "Biuro", "Dzialka", "Dom", "inne"});
        
        jcbENid.addItemListener((ItemEvent e) -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                String name1 = ((JComboBox)e.getSource()).getSelectedItem().toString();
//                 int id = (int)ptm.getValueAt(jtProperties.getSelectedRow(), 0);
                if (!name1.isEmpty()) {
//                 controller.updateByTid(id, name);
                }
            }
        });
        
        
        
        jtfEName.addKeyListener(new KeyAdapter(){
             @Override
             public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER){
                   String name = ((JTextField)e.getSource()).getText();
//                   int id = (int)ptm.getValueAt(jtProperties.getSelectedRow(), 0);
                    if(!name.equals(" ")){
//                       controller.updateByName(id, name);
                    }
                }
             }
        });
//        jtProperties.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(jtfEName));
//        jtProperties.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(jcbENid));
    
    }

    
   

    private class EstatesSelectionListener implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
////    currentSelectedRowIndex = jtProperties.getSelectedRow();
           jpView.setVisible(true);
           if(currentSelectedRowIndex > -1){
//           jlabResourceEmptyPlace.setText(String.valueOf(jtProperties.getValueAt(currentSelectedRowIndex, 2)));
           }
           
        }

     

    }

 
    private void btAddPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPropertyActionPerformed
        jdAddProperty.setVisible(true);
    }//GEN-LAST:event_btAddPropertyActionPerformed

    private void jbAddEstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddEstateActionPerformed
        String name = jtfDName.getText();
        String tid = jcbTid.getSelectedItem().toString();
        String nid = jcbNid.getSelectedItem().toString();
        double price = Double.parseDouble(jtfDPrice.getText());
        double surface = Double.parseDouble(jtfDSurface.getText());
        int rooms = (int) Integer.parseInt(jtfDRooms.getText());
        String description = jtaDDescription.getText();
        String country = jtfDCountry.getText();
        String province = jtfDProvince.getText();
        String community = jtfDCommunity.getText();
        String county = jtfDCounty.getText();
        String city = jtfDCity.getText();
        String street = jtfDStreet.getText();
        String path;

        if (img != null) {
            path = AppRunner.IMG_CAT + img.getName();

        } else {
            path = AppRunner.IMG_TMP_CAT + AppRunner.NO_IMG_FILE_NAME + "." + AppRunner.NO_IMG_FILE_EXT;

        }

        controller.getModel().setImg(path);
        controller.getModel().setName(name);
        controller.getModel().setTid(tid);
        controller.getModel().setNid(nid);
        controller.getModel().setPrice(price);
        controller.getModel().setSurface(surface);
        controller.getModel().setRooms(rooms);
        controller.getModel().setDescription(description);
        controller.getModel().setCountry(country);
        controller.getModel().setProvince(province);
        controller.getModel().setCounty(county);
        controller.getModel().setCity(city);
        controller.getModel().setStreet(street);
        controller.addEstate();


    }//GEN-LAST:event_jbAddEstateActionPerformed

    private void jtfDCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDCityActionPerformed

    private void jbCancelEstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelEstateActionPerformed
        int btCancel = JOptionPane.YES_NO_OPTION;
        int dialogResult;
        dialogResult = JOptionPane.showConfirmDialog(jdAddProperty, "Czy napewno chcesz anulowac dodawanie nieruchomosci?", "Uwaga!", btCancel);
        if (dialogResult == JOptionPane.YES_OPTION) {
            jdAddProperty.dispose();
        }
    }//GEN-LAST:event_jbCancelEstateActionPerformed

    private void btChoosePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChoosePicActionPerformed
        JFileChooser pic = new JFileChooser();
        pic.addChoosableFileFilter(new FileNameExtensionFilter(".*jpg", "jpg"));
        pic.addChoosableFileFilter(new FileNameExtensionFilter(".*png", "png"));
        pic.addChoosableFileFilter(new FileNameExtensionFilter(".*bmp", "bmp"));
        pic.addChoosableFileFilter(new FileNameExtensionFilter(".*gif", "gif"));
        int returnVal = pic.showDialog(jdAddProperty, "Wybierz zdiecie:");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            img = pic.getSelectedFile();
        }
    }//GEN-LAST:event_btChoosePicActionPerformed
    public JDialog getDialogInstance() {
        return jdAddProperty;
    }

    private void saveImage(File file) {
        BufferedImage imag = new BufferedImage(IMG_W, IMG_H, BufferedImage.TYPE_INT_ARGB);
        String ext = getFileExtension(file);
        try {
            imag = ImageIO.read(file);
        } catch (IOException ex) {
            Logger.getLogger(EstateDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ImageIO.write(imag, ext, new File(AppRunner.IMG_CAT, file.getName()));
        } catch (IOException ex) {
            Logger.getLogger(EstateDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private String getFileExtension(File file) {
        String name = file.getName();
        try {
            return name.substring(name.lastIndexOf(".") + 1);
        } catch (Exception e) {
            return "";
        }
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddProperty;
    private javax.swing.JButton btChoosePic;
    private javax.swing.JButton btExcel;
    private javax.swing.JButton btPDF;
    private manager.view.estate.panel.EquipmentPanel equipmentPanel1;
    private manager.view.estate.panel.FillterPanel fillterPanel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jbAddEstate;
    private javax.swing.JButton jbCancelEstate;
    private javax.swing.JComboBox<String> jcbNid;
    private javax.swing.JComboBox<String> jcbTid;
    private javax.swing.JDialog jdAddProperty;
    private javax.swing.JLabel jlabChoosePic;
    private javax.swing.JLabel jlabDCity;
    private javax.swing.JLabel jlabDCommunity;
    private javax.swing.JLabel jlabDCountry;
    private javax.swing.JLabel jlabDCounty;
    private javax.swing.JLabel jlabDNameEstate;
    private javax.swing.JLabel jlabDNewEstate;
    private javax.swing.JLabel jlabDPrice;
    private javax.swing.JLabel jlabDProvince;
    private javax.swing.JLabel jlabDStreet;
    private javax.swing.JLabel jlabDTid;
    private javax.swing.JLabel jlabResourceEmptyPlace;
    private javax.swing.JLabel jlabResourceName;
    private javax.swing.JPanel jpDProperty;
    private javax.swing.JPanel jpView;
    private javax.swing.JPanel jpViewProperties;
    private javax.swing.JScrollPane jspDDescription;
    private javax.swing.JSplitPane jspProperties;
    private javax.swing.JTextArea jtaDDescription;
    private javax.swing.JTextField jtfDCity;
    private javax.swing.JTextField jtfDCommunity;
    private javax.swing.JTextField jtfDCountry;
    private javax.swing.JTextField jtfDCounty;
    private javax.swing.JTextField jtfDName;
    private javax.swing.JTextField jtfDPrice;
    private javax.swing.JTextField jtfDProvince;
    private javax.swing.JTextField jtfDRooms;
    private javax.swing.JTextField jtfDStreet;
    private javax.swing.JTextField jtfDSurface;
    private javax.swing.JTree jtrResources;
    private manager.view.estate.panel.MediaPanel mediaPanel1;
    private manager.view.estate.panel.PersonPanel personsPanel;
    private manager.view.estate.panel.RenovationPanel renovationPanel1;
    private manager.view.estate.panel.TablePanel tablePanel;
    private javax.swing.JToolBar tbProperties;
    // End of variables declaration//GEN-END:variables
    @Override
    public void update(Observable o, Object arg) {
     

    }

}
