/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager.view.estate.panel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import manager.controller.AppRunner;
import manager.controller.EstateController;
import manager.controller.PersonController;
import manager.model.resources.PersonModel;

/**
 *
 * @author virtus
 */
public class PersonPanel extends javax.swing.JPanel {

    private final PersonController controller;
    private static final int TENANT_INDEX = 0;
    private static final int WORKER_INDEX = 1;
    private static final String TENANT_TEXT = "Czynsz dla lokatora:";
    private static final String WORKER_TEXT = "Pensja dla pracownika:";

    /**
     * Creates new form PersonsPanel
     */
    public PersonPanel() {
        controller = null;
        initComponents();

    }

    public PersonPanel(PersonController controller) {
        this.controller = controller;
        initComponents();
        setupComponent();
        setupListener();
    }

    private void setupListener() {
        btAddPerson.addActionListener(new AddPersonActionListener());
        jcbFunction.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {

                if (ie.getStateChange() == ItemEvent.SELECTED) {
                    int selectedIndex = ((JComboBox) ie.getSource()).getSelectedIndex();
                    changeRole(selectedIndex);
                }
            }

        });
    }

    private void setupComponent() {
        int selectedIndex = jcbFunction.getSelectedIndex();
        changeRole(selectedIndex);
    }

    private void changeRole(int index) {
        if (index == TENANT_INDEX) {
            changeAmountText(TENANT_TEXT);
        } else if (index == WORKER_INDEX) {
            changeAmountText(WORKER_TEXT);
        }
    }

    private void changeAmountText(String text) {
        jlabAmount.setText(text);
    }

    private class AddPersonActionListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            PersonModel model = controller.getPersonModel();
            String lastName = jtfLastName.getText();
            String name = jtfName.getText();
            String pesel = jtfPesel.getText();
            String periodText = jtfPeriod.getText();
            double rent = 0.0;
            double salary = 0.0;
            String desc = jtaDesc.getText();
            int period = 0;
            String role = jcbFunction.getSelectedItem().toString();
            int nid = ((EstateController)AppRunner.estateController).getTablePanel().getCurrentId();
            System.out.println(nid);
            int roleIndex = jcbFunction.getSelectedIndex();
            String amount = jtfAmount.getText();
           
            if (roleIndex == TENANT_INDEX) {
                if (!amount.equals("")) {
                    rent = Double.parseDouble(amount);
                }
                salary = 0.0;
            } else if (roleIndex == WORKER_INDEX) {
                if (!amount.equals("")) {
                    salary = Double.parseDouble(amount);
                }
                rent = 0.0;
            }
            
            if(!periodText.equals("")){
                period = Integer.parseInt(periodText);
            }
            
            model.setName(name);
            model.setLastName(lastName);
            model.setPesel(pesel);
            model.setRent(rent);
            model.setSalary(salary);
            model.setDesc(desc);
            model.setRent(rent);
            model.setSalary(salary);
            model.setPeriod(period);
            model.setFunction(role);
            model.setNid(nid);
            
            controller.addPerson(model);
        }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabName = new javax.swing.JLabel();
        jlabLastName = new javax.swing.JLabel();
        jlabPesel = new javax.swing.JLabel();
        jtfLastName = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jtfPesel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jcbFunction = new javax.swing.JComboBox<>();
        btAddPerson = new javax.swing.JButton();
        jlabAmount = new javax.swing.JLabel();
        jtfAmount = new javax.swing.JTextField();
        jlabPeriod = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfPeriod = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);

        jlabName.setText("Imie:");

        jlabLastName.setText("Nazwisko:");

        jlabPesel.setText("Pesel:");

        jLabel17.setText("Rola:");

        jcbFunction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lokator", "Pracownik", "Wlasciciel" }));

        btAddPerson.setText("Dodaj");

        jtfAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAmountActionPerformed(evt);
            }
        });

        jlabPeriod.setText("Czas trwania umowy:");

        jLabel4.setText("Opis:");

        jtaDesc.setColumns(20);
        jtaDesc.setRows(5);
        jtaDesc.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtaDesc);

        jLabel5.setText("ms");

        jLabel6.setText("ms");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabLastName)
                            .addComponent(jlabPesel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jtfLastName)
                            .addComponent(jtfPesel)))
                    .addComponent(jlabName))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabAmount, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabPeriod, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfAmount)
                            .addComponent(jcbFunction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAddPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPeriod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabName)
                    .addComponent(jtfName)
                    .addComponent(jLabel17)
                    .addComponent(jcbFunction))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabLastName)
                    .addComponent(jtfLastName)
                    .addComponent(jlabAmount)
                    .addComponent(jtfAmount)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabPesel)
                            .addComponent(jtfPesel)
                            .addComponent(jLabel6)
                            .addComponent(jtfPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabPeriod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(btAddPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAmountActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddPerson;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbFunction;
    private javax.swing.JLabel jlabAmount;
    private javax.swing.JLabel jlabLastName;
    private javax.swing.JLabel jlabName;
    private javax.swing.JLabel jlabPeriod;
    private javax.swing.JLabel jlabPesel;
    private javax.swing.JTextArea jtaDesc;
    private javax.swing.JTextField jtfAmount;
    private javax.swing.JTextField jtfLastName;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPeriod;
    private javax.swing.JTextField jtfPesel;
    // End of variables declaration//GEN-END:variables
}
